###########################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: admin
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5             # 最小连接数   最好是不要设置最小最大都是10（默认）
      maximum-pool-size: 20          # 最大连接数
      auto-commit: true              # 自动提交
      idle-timeout: 600000             # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000             # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: select 1
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.lzq.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
    max-http-header-size: 80KB

mapper:
  mappers: com.lzq.my.mapper.MyMapper
  not-empty: true
  identity: MYSQL